config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show]
  resources :statements

  root to: "home#index"
end

app/models/statement.rb
# frozen_string_literal: true

class Statement < ApplicationRecord
  belongs_to :statement_type

  STATUSES = %w(pending accept decline)

  validates :status, inclusion: { in: STATUSES },
            presence: true
  validates_comparison_of :end_date, greater_than_or_equal_to: :start_date

  def type
    statement_type.name
  end

  def user
    User.find(user_id)
  end
end

app/models/statement_type.rb
# frozen_string_literal: true

class StatementType < ApplicationRecord
end

app/controllers/statements_controller.rb
# frozen_string_literal: true

class StatementsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_statement, only: %i[show edit update destroy]
  before_action :set_statement_types, only: %i[create new]

  def show; end

  def edit
    render :edit
  end

  def new
    @statement = Statement.new
    render :new
  end

  def create
    @statement = Statement.new(statement_params)

    @statement.user_id = current_user.id
    @statement.status = 'pending'

    if @statement.save
      AdminNotificationMailer.with(statement: @statement).new_admin_notification_email.deliver_later

      flash[:success] = "New statement successfully added!"
      redirect_to user_path(current_user)
    else
      flash.now[:error] = "Statement creation failed"
      render :new
    end
  end

  def update
    if !current_user.admin? && @statement.update(statement_params)
      AdminNotificationMailer.with(statement: @statement).new_admin_notification_email.deliver_later

      flash[:success] = "Statement successfully updated!"
      redirect_to user_path(current_user)
    elsif current_user.admin? && @statement.update(statement_admin_params)
      NotificationMailer.with(statement: @statement).new_notification_email.deliver_later

      flash[:success] = "Statement successfully updated!"
      redirect_to user_path(current_user)
    else
      flash.now[:error] = "Statement update failed"
      render :edit
    end
  end

  def destroy
    @statement.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_statement
    @statement = Statement.find(params[:id])
  end

  def set_statement_types
    @statement_types = StatementType.all
  end

  def statement_params
    params.require(:statement).permit(
      :start_date,
      :end_date,
      :statement_type_id
    )
  end

  def statement_admin_params
    params.require(:statement).permit(
      :status
    )
  end
end

app/views/statements/edit.html.erb
<div class='container'>
  <div class='col-md-6 offset-md-3 mb-5'>
    <h1>Edit Statement: "<%= @statement.type %>"</h1>

    <!-- TODO необходимо отсюда вынести статусы -->
    <% disable_status = @statement.status.match?('accept' || 'decline') ? true : false %>

    <% if current_user.role != 'admin' %>
      <div class='container'>
        <%= form_with model: @statement, method: :patch, local: true do |f| %>
          <div class='mb-3'>
            <label for='status_field' class='form-label'>Status</label>
            <%= f.text_field :status, class: 'form-control', disabled: true %>
          </div>
          <div class='mb-3'>
            <label for='start_date_field' class='form-label'>Start Date</label>
            <%= f.date_field :start_date, class: 'form-control', disabled: disable_status, required: true %>
          </div>
          <div class='mb-3'>
            <label for='end_date_field' class='form-label'>End Sate</label>
            <%= f.date_field :end_date, class: 'form-control', disabled: disable_status, required: true %>
          </div>

          <%= f.submit class: 'btn btn-primary', disabled: disable_status %>
        <% end %>
        <%= button_to "Destroy", @statement,
                      method: :delete,
                      class: 'btn btn-danger mt-2',
                      data: { confirm: "Are you sure?" } %>

        <%= link_to 'Statements', user_path(current_user),
                    rel: 'noopener noreferrer',
                    class: 'btn btn-outline-primary mt-2' %>
      </div>
    <% else %>
      <div class='container'>
        <%= form_with model: @statement, method: :patch, local: true do |f| %>
          <div class='mb-3'>
            <label for='status_field' class='form-label'>Status</label>
            <%= f.select(:status, Statement::STATUSES.map { |value| [value, value] },
                         class: 'form-select form-select-lg mb-3', required: true) %>
          </div>
          <div class='mb-3'>
            <label for='start_date_field' class='form-label'>Start Date</label>
            <%= f.date_field :start_date, class: 'form-control', disabled: true %>
          </div>
          <div class='mb-3'>
            <label for='end_date_field' class='form-label'>End Sate</label>
            <%= f.date_field :end_date, class: 'form-control', disabled: true %>
          </div>

          <%= f.submit class: 'btn btn-primary' %>
        <% end %>

        <%= link_to 'Statements', user_path(current_user),
                    rel: 'noopener noreferrer',
                    class: 'btn btn-outline-primary mt-2' %>
      </div>
    <% end %>
  </div>
</div>

app/views/statements/new.html.erb
<div class='container'>
  <div class='col-md-6 offset-md-3 mb-5'>
    <div class='container'>
      <h1>Create New Statement</h1>
      <%= form_with model: @statement, url: statements_path, method: :post, local: true do |f| %>
        <div class='mb-3'>
          <label for='statement_type_field' class='form-label'>Type</label>
          <%= f.select :statement_type_id,
                       options_from_collection_for_select(@statement_types, 'id', 'name'),
                       { prompt: 'Select a type' },
                       class: 'form-select form-select-lg mb-3', required: true %>
        </div>

        <div class='mb-3'>
          <label for='status_field' class='form-label'>Start date</label>
          <%= f.date_field :start_date, class: 'form-control', required: true %>
        </div>
        <div class='mb-3'>
          <label for='status_field' class='form-label'>End date</label>
          <%= f.date_field :end_date, class: 'form-control', required: true %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

      <%= link_to 'Statements', user_path(current_user),
                  rel: 'noopener noreferrer',
                  class: 'btn btn-outline-primary mt-2' %>
    </div>
  </div>
</div>